/* Generated By:JavaCC: Do not edit this line. SparqlParserConstants.java */
package io.sparqlar.parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SparqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COND = 9;
  /** RegularExpression Id. */
  int N = 12;
  /** RegularExpression Id. */
  int AN = 27;
  /** RegularExpression Id. */
  int URI = 28;
  /** RegularExpression Id. */
  int LITERAL = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"ASK\"",
    "\"SELECT\"",
    "\"DISTINCT\"",
    "\"WHERE\"",
    "\"{\"",
    "<COND>",
    "\"}\"",
    "\"LIMIT \"",
    "<N>",
    "\"*\"",
    "\".\"",
    "\"UNION\"",
    "\"APPROX\"",
    "\"(\"",
    "\")\"",
    "\"RELAX\"",
    "\"FLEX\"",
    "\"OPTIONAL\"",
    "\"/\"",
    "\"|\"",
    "\"PREFIX\"",
    "\":\"",
    "\"?\"",
    "<AN>",
    "<URI>",
    "<LITERAL>",
  };

}
