package io.sparqlar.ui;

import io.sparqlar.sparqlardc.terms.URI;

import javax.swing.*;
import java.awt.*;
import java.util.HashSet;
import java.util.List;

public class ChoosePredicates extends JDialog {
    private final HashSet<URI> toKeepSet;
    private final HashSet<URI> toApproxSet;
    private JList<URI> toKeep;
    private JList<URI> toApprox;
    private JLabel helpText;
    private JButton keepButton;
    private JButton approxButton;
    private JButton OKButton;
    private JPanel choosePredPanel;


    public ChoosePredicates(Frame parent, boolean modal, HashSet<URI> allApproximated, HashSet<URI> toNotApproximate, boolean del) {
        super(parent, modal);
        allApproximated.removeAll(toNotApproximate);
        this.toApproxSet = allApproximated;
        this.toKeepSet = toNotApproximate;
        setListData();
        if (del)
            helpText.setText("The left side shows the predicates that will be deleted.\n Move them on the right side using the arrow if you don't want them to be deleted.");
        else
            helpText.setText("The left side shows the predicates that will be substituted.\n Move them on the right side using the arrow if you don't want them to be substituted.");
        keepButton.addActionListener(e -> {
            List<URI> selectedValuesList = toApprox.getSelectedValuesList();
            toKeepSet.addAll(selectedValuesList);
            toApproxSet.removeAll(selectedValuesList);
            setListData();
        });
        approxButton.addActionListener(e -> {
            List<URI> selectedValuesList = toKeep.getSelectedValuesList();
            toKeepSet.removeAll(selectedValuesList);
            toApproxSet.addAll(selectedValuesList);
            setListData();
        });
        OKButton.addActionListener(e -> dispose());
        setContentPane(choosePredPanel);
        pack();
        setVisible(true);
    }

    private void setListData() {
        toApprox.setListData(toApproxSet.toArray(new URI[0]));
        toKeep.setListData(toKeepSet.toArray(new URI[0]));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        choosePredPanel = new JPanel();
        choosePredPanel.setLayout(new GridBagLayout());
        helpText = new JLabel();
        helpText.setText("Label");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        choosePredPanel.add(helpText, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridheight = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        choosePredPanel.add(scrollPane1, gbc);
        toApprox = new JList();
        scrollPane1.setViewportView(toApprox);
        final JScrollPane scrollPane2 = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.gridheight = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        choosePredPanel.add(scrollPane2, gbc);
        toKeep = new JList();
        scrollPane2.setViewportView(toKeep);
        keepButton = new JButton();
        keepButton.setText("---->");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        choosePredPanel.add(keepButton, gbc);
        approxButton = new JButton();
        approxButton.setText("<----");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        choosePredPanel.add(approxButton, gbc);
        OKButton = new JButton();
        OKButton.setText("OK");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        choosePredPanel.add(OKButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return choosePredPanel;
    }
}
