package io.sparqlar.ui;

import io.sparqlar.rewriting.QueryCost;
import io.sparqlar.sparqlardc.CQSPARQL;

import javax.swing.*;
import java.awt.*;
import java.util.List;

public class QueryList extends JDialog {
    private JLabel queryCost;
    private JList<QueryCost<CQSPARQL>> queryList;
    private JPanel queryListPanel;

    public QueryList(Frame parent, boolean modal, List<QueryCost<CQSPARQL>> queryCosts) {
        super(parent, modal);
        queryList.setListData(queryCosts.toArray(new QueryCost[0]));
        queryList.addListSelectionListener(e -> queryCost.setText(Float.toString(queryList.getSelectedValue().getCost())));
        setContentPane(queryListPanel);
        pack();
        setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        queryListPanel = new JPanel();
        queryListPanel.setLayout(new GridBagLayout());
        queryListPanel.setMinimumSize(new Dimension(1000, 300));
        queryListPanel.setPreferredSize(new Dimension(1000, 300));
        final JScrollPane scrollPane1 = new JScrollPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        queryListPanel.add(scrollPane1, gbc);
        queryList = new JList();
        scrollPane1.setViewportView(queryList);
        final JLabel label1 = new JLabel();
        label1.setText("Query Cost:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        queryListPanel.add(label1, gbc);
        queryCost = new JLabel();
        queryCost.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        queryListPanel.add(queryCost, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return queryListPanel;
    }
}
